#!/bin/sh
#
# AIDE check helper script
#

#
# Config
#

# ID string for log messages
name=aide-check
# Initialize new aide database if needed, yes or no.
init_db=yes
# Update aide database after check, yes or no.
update_db=yes
# Verbose if check ok, yes or no.
ok_verbose=no
# Temp file path
tempfile=/tmp/.aide-check.$$

#
# Main
#
log_msg() {
  prio=$1 ; shift
  logger -p $prio "$name: $@"
}

log_output() {
  prio=$1 ; shift
  cat $tempfile | sed -e 's/^/'$name': /' -e 's/\t/  /g' | logger -p $prio
}

log_msg info "Starting aide check..."

if [ "$init_db" != "yes" -a ! -f /var/lib/aide/aide.db.gz ]; then
  log_msg alert "aide database not initialized, aborting check!"
  exit 1
fi

if [ "$init_db" = "yes" -a ! -f /var/lib/aide/aide.db.gz ]; then
  log_msg alert "Initializing new aide database..."
  rc=0
  aide --init > $tempfile 2>&1
  rc=$((rc+$?))
  mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz >> $tempfile 2>&1
  rc=$((rc+$?))
  if [ $rc -ne 0 ]; then
    rm -f /var/lib/aide/aide.db.gz /var/lib/aide/aide.db.new.gz
    log_msg alert "Failed to initialize new aide database, aborting check!"
    log_output alert
    rm -f $tempfile
    exit 1
  fi
  log_msg alert "New aide database initialized ok!"
  log_output alert
  rm -f $tempfile
fi

log_msg info "Running aide check..."
rc=0
[ "$update_db" = "yes" ] && param=--update || param=--check
aide $param > $tempfile 2>&1
rc=$((rc+$?))

if [ $rc -eq 0 ]; then
  log_msg notice "No differences found in aide check."
  if [ "$ok_verbose" = "yes" ]; then
    log_output info
  fi
fi

if [ $rc -ne 0 ]; then
  log_msg alert "Differences found in aide check!"
  log_output alert
fi
rm -f $tempfile

if [ "$update_db" = "yes" -a $rc -ne 0 ]; then
  log_msg alert "Updating aide database..."
  mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz >> $tempfile 2>&1
  if [ $? -ne 0 ]; then
    rm -f /var/lib/aide/aide.db.new.gz
    log_msg alert "Failed to update aide database, aborting!"
    log_output alert
    rm -f $tempfile
    exit 1
  fi
else
  rm -f /var/lib/aide/aide.db.new.gz
  log_msg info "Not updating aide database."
fi

log_msg info "Check complete."
