# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/set_fact_module.html
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/set_stats_module.html
#
# Later the below set data can be accessed like this:
#    - name: Display per-host variable
#      ansible.builtin.debug:
#        var: host_data[inventory_hostname]['rebooted']
#      run_once: true
---
- name: Set per-host data for playbook/role and workflow
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Set workflow data, part I
      vars:
        # Add some difference in data just to show data is indeed per-host
        updated: "{{ true if ansible_play_batch.index(inventory_hostname) is even else false }}"
      ansible.builtin.set_stats:
        data:
          host_data: "{{ host_data | default({})
                         | combine({inventory_hostname: {'updated': updated, 'running': true}}) }}"
      when: tower_job_id is defined

    - name: Set workflow data, part II
      vars:
        # Add some difference in data just to show data is indeed per-host
        rebooted: "{{ false if ansible_play_batch.index(inventory_hostname) is even else true }}"
      ansible.builtin.set_stats:
        data:
          host_data: "{{ host_data | default({})
                         | combine({inventory_hostname: {'rebooted': rebooted}}) }}"
      when: tower_job_id is defined

    - name: Set playbook data, part I
      vars:
        # Add some difference in data just to show data is indeed per-host
        updated: "{{ true if ansible_play_batch.index(inventory_hostname) is even else false }}"
      ansible.builtin.set_fact:
        host_data: "{{ host_data | default({})
                       | combine({inventory_hostname: {'updated': updated, 'running': true}}, recursive=true) }}"
      when: tower_job_id is not defined

    - name: Set playbook data, part II
      vars:
        # Add some difference in data just to show data is indeed per-host
        rebooted: "{{ false if ansible_play_batch.index(inventory_hostname) is even else true }}"
      ansible.builtin.set_fact:
        host_data: "{{ host_data | default({})
                       | combine({inventory_hostname: {'rebooted': rebooted}}, recursive=true) }}"
      when: tower_job_id is not defined

    - name: Display data per-host variable
      ansible.builtin.debug:
        var: host_data[inventory_hostname]['rebooted']
        #var: hostvars[inventory_hostname]['host_data'][inventory_hostname]['rebooted']
      #run_once: true
      when: tower_job_id is not defined
