---
- name: Auxiliary server test
  hosts: localhost
  become: false
  gather_facts: false
  vars:
    aux_servers:
      - 192.168.122.118
      - 192.168.122.119
      - 192.168.122.120
  tasks:
    - name: Check available auxiliary servers
      ping:
      register: ping_results
      ignore_unreachable: true
      loop: "{{ aux_servers }}"
      delegate_to: "{{ item }}"

    - name: Set the auxiliary server to use
      vars:
        servers_ok: "{{ ping_results.results
                        | selectattr('failed', 'defined')
                        | selectattr('failed', 'equalto', false)
                        | map(attribute='item') }}"
      set_fact:
        aux_server: "{{ servers_ok | random | default('') }}"
      failed_when: servers_ok | length < 1

    - name: Display the selected auxiliary server
      debug:
        var: aux_server
