# https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html
# https://jinja.palletsprojects.com/en/3.0.x/templates/#list-of-builtin-filters
# https://docs.ansible.com/ansible/latest/user_guide/complex_data_manipulation.html
---
- name: Miscellaneous Ansible examples
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  tasks:
    - name: Display effective remote user
      vars:
        conn_user: "{{ 'ansible_' + ansible_connection + '_user' }}"
        remo_user: "{{ vars[conn_user] | default(ansible_user) | default(lookup('env', 'USER')) }}"
      ansible.builtin.debug:
        msg: "Remote user is {{ remo_user }}"

    - name: Display Ansible configuration variables
      ansible.builtin.debug:
        msg: >-
          {{ hostvars[inventory_hostname]
             | dict2items
             | selectattr('key', 'match', '^ansible_')
             | rejectattr('key', 'equalto', 'ansible_facts')
             | sort(attribute='key')
             | items2dict
          }}
      run_once: true

    - name: Display variable names
      ansible.builtin.debug:
        msg: "{{ lookup('varnames', '.+') | split(',') | sort }}"

    - name: Display variables
      ansible.builtin.debug:
        var: vars

    - name: Display facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: End here
      ansible.builtin.meta: end_play

    - name: Create list from items
      ansible.builtin.set_fact:
        a_list: "{{ a_list | default([]) + [item] }}"
      loop:
        - one
        - two
        - three

    - name: Display list from items
      ansible.builtin.debug:
        var: a_list

    - name: Create dict from items
      ansible.builtin.set_fact:
        a_dict: "{{ a_dict | default({}) | combine({item: ansible_facts.distribution}) }}"
      loop: "{{ ansible_play_batch + ansible_run_tags }}"

    - name: Display dict from items
      ansible.builtin.debug:
        var: a_dict

    - name: Test distribution major version
      ansible.builtin.debug:
        msg: "{{ ansible_facts.distribution_major_version | int >= 8 is true }}"
      when: ansible_facts.distribution_major_version | int >= 8

    - name: Set fact based on condition
      ansible.builtin.set_fact:
        tuned_profile: "{{ 'virtual-guest' if ansible_facts.virtualization_role == 'guest' else 'throughput-performance' }}"

    - name: Use distribution specific variable to install packages
      vars:
        selinux_package_lists:
          rhel7:
            - libselinux-python
            - libsemanage-python
            - policycoreutils-python
            - selinux-policy-targeted
            - setools-console
          default:
            - python3-libselinux
            - python3-libsemanage
            - policycoreutils-python-utils
            - selinux-policy-targeted
            - setools-console
        distro_id: "{{ 'rhel' + ansible_facts.distribution_major_version }}"
        package_set: "{{ 'default' if distro_id not in selinux_package_lists else distro_id }}"
        selinux_packages: "{{ selinux_package_lists[package_set] }}"
      ansible.builtin.dnf:
        name: "{{ selinux_packages }}"
        state: present
      when: false

    # Example of configuring and re/starting a service below
    - name: Disallow zone drifting
      ansible.builtin.replace:
        dest: /etc/firewalld/firewalld.conf
        regexp: '^AllowZoneDrifting=yes'
        replace: 'AllowZoneDrifting=no'
      register: firewalld_config
      when: false

    - name: Enable firewalld service
      ansible.builtin.service:
        name: firewalld
        enabled: true
      when: false

    - name: Start firewalld service
      ansible.builtin.service:
        name: firewalld
        state: started
      register: service_start
      when: false

    - name: Reload firewalld to apply configuration changes
      ansible.builtin.service:
        name: firewalld
        state: reloaded
      when:
        - service_start is not changed
        - firewalld_config is changed
    # Example of configuring and re/starting a service above
