---
- name: Windows connectivity test
  hosts: all
  become: false
  gather_facts: false
  vars:
    #
    # Ansible WinRM configuration
    #
    ansible_connection: winrm
    ansible_pipelining: true
    ansible_winrm_port: 5985
    ansible_winrm_scheme: http
    ansible_winrm_transport: ntlm
    ansible_winrm_message_encryption: always
    ansible_winrm_server_cert_validation: ignore

    ansible_winrm_user: Administrator
    ansible_winrm_password: Foobar_12

    ansible_become_method: runas
    #ansible_become_user: Administrator

    #
    # Ansible Windows/SSH configuration
    #
    #ansible_user: Administrator
    #ansible_password: Foobar_12
    #ansible_shell_type: powershell
    #ansible_become_method: runas
    #ansible_become_user: Administrator

  tasks:
    - name: Check host reachable
      ansible.windows.win_wait_for:
        port: 5985
        timeout: 30

    - name: Check host access
      ansible.windows.win_ping:

    - name: Check user privileges
      ansible.windows.win_whoami:
      register: whoami_output
      failed_when: whoami_output.privileges.SeDebugPrivilege is not search('enabled')
      changed_when: false
