---
- name: Windows connectivity test
  hosts: all
  become: false
  gather_facts: false
  vars:
    admin_group: Administrators
    gpo_check: true

    #
    # Ansible WinRM configuration
    #
    #ansible_connection: winrm
    #ansible_winrm_port: 5985
    #ansible_winrm_scheme: http
    #ansible_winrm_transport: ntlm
    #ansible_winrm_message_encryption: always
    #ansible_winrm_server_cert_validation: ignore

    #ansible_winrm_user: Administrator
    #ansible_winrm_password: Foobar_12

    #
    # Ansible psrp configuration
    #
    ansible_connection: psrp
    ansible_psrp_port: 5985
    ansible_psrp_protocol: http
    ansible_psrp_auth: ntlm
    ansible_psrp_message_encryption: always
    ansible_psrp_cert_validation: ignore

    ansible_psrp_user: Administrator
    ansible_winrm_password: Foobar_12

    #
    # Ansible Windows/SSH configuration
    #
    #ansible_user: Administrator
    #ansible_password: Foobar_12
    #ansible_shell_type: powershell
    #ansible_ssh_common_args: -o GSSAPIDelegateCredentials=yes

    #
    # Common Windows connection parameters
    #
    ansible_become_method: runas
    #ansible_become_user: Administrator

  tasks:
    - name: Display Ansible runtime essentials
      vars:
        output:
          ansible_version: "{{ ansible_version }}"
          ansible_config_file: "{{ ansible_config_file }}"
          ansible_inventory_sources: "{{ ansible_inventory_sources }}"
          ansible_playbook_python: "{{ ansible_playbook_python }}"
          ansible_play_hosts_all: "{{ ansible_play_hosts_all }}"
          ansible_play_batch: "{{ ansible_play_batch }}"
      ansible.builtin.debug:
        msg: "{{ output }}"
      run_once: true

    - name: Set remote connection port
      vars:
        conn_port: "{{ 'ansible_' + ansible_connection + '_port' }}"
      ansible.builtin.set_fact:
        remo_port: "{{ lookup('vars', conn_port, default='')
                       | default(ansible_port, true)
                       | default('22', true) }}"

    - name: Display connection parameters
      vars:
        conn_user: "{{ 'ansible_' + ansible_connection + '_user' }}"
        remo_user: "{{ lookup('vars', conn_user, default='')
                       | default(ansible_user, true)
                       | default(lookup('env', 'USER'), true) }}"
      ansible.builtin.debug:
        msg: "Attempting to connect as {{ remo_user }} to {{ inventory_hostname }}:{{ remo_port }}"

    - name: Check host reachable
      vars:
        ansible_connection: local
        ansible_shell_type: sh
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ remo_port }}"
        timeout: 10
      delegate_to: localhost

    - name: Check host access
      ansible.windows.win_ping:

    - name: Check user privileges
      ansible.windows.win_whoami:
      register: whoami_output

    - name: Verify user is in group {{ admin_group }}
      ansible.builtin.assert:
        that:
          - admin_group in whoami_output.groups | map(attribute='account_name')
        quiet: true
        fail_msg: "User is not in the group {{ admin_group }}."

    - name: Verify user has privilege SeDebugPrivilege
      ansible.builtin.assert:
        that:
          - "'SeDebugPrivilege' in whoami_output.privileges or
              whoami_output.privileges.SeDebugPrivilege is search('enabled')"
        quiet: true
        fail_msg: "User does not have the privilege SeDebugPrivilege."

    - name: Ensure become works if become user defined
      become: true
      become_user: "{{ ansible_become_user }}"
      ansible.windows.win_whoami:
      when: ansible_become_user is defined

    - name: Run Group Policy Result tool
      check_mode: false
      ansible.windows.win_command: gpresult.exe /scope user /v
      register: gpresult_info
      changed_when: false
      when: gpo_check | bool

    - name: Display Group Policy Result tool report
      ansible.builtin.debug:
        msg: "{{ gpresult_info.stdout_lines }}"
      when: gpo_check | bool

    - name: Run Group Policy Result tool with become
      become: true
      become_user: "{{ ansible_become_user }}"
      check_mode: false
      ansible.windows.win_command: gpresult.exe /scope user /v
      register: gpresult_info
      changed_when: false
      when:
        - ansible_become_user is defined
        - gpo_check | bool

    - name: Display Group Policy Result tool report with become
      ansible.builtin.debug:
        msg: "{{ gpresult_info.stdout_lines }}"
      when:
        - ansible_become_user is defined
        - gpo_check | bool
