---
- name: Ansible debug playbook
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Display Ansible runtime essentials
      vars:
        output:
          ansible_version: "{{ ansible_version }}"
          ansible_config_file: "{{ ansible_config_file }}"
          ansible_inventory_sources: "{{ ansible_inventory_sources }}"
          ansible_playbook_python: "{{ ansible_playbook_python }}"
          ansible_play_hosts_all: "{{ ansible_play_hosts_all }}"
          ansible_play_batch: "{{ ansible_play_batch }}"
      ansible.builtin.debug:
        msg: "{{ output }}"
      run_once: true

    - name: Display Ansible host groups
      ansible.builtin.debug:
        var: groups
      run_once: true

    - name: Set variable names to display
      ansible.builtin.set_fact:
        var_names: "{{ lookup('ansible.builtin.varnames', '.+', wantlist=true)
                       | reject('in', ['ansible_facts', 'hostvars', 'play_hosts', 'vars'])
                       | sort }}"

    - name: Display variable names
      ansible.builtin.debug:
        msg: "{{ var_names }}"

    - name: Display variable values
      vars:
        var_values: |
          {% for key in var_names %}
          {{ key }}: {{ lookup('ansible.builtin.vars', key) }}
          {% endfor %}
      ansible.builtin.debug:
        msg: "{{ var_values | from_yaml }}"

    - name: Read Ansible changed configuration
      ansible.builtin.shell: ansible-config dump --changed-only --f display --t all | grep -v token
      register: changed_config
      changed_when: false
      delegate_to: localhost
      run_once: true

    - name: Display Ansible changed configuration
      ansible.builtin.debug:
        msg: "{{ changed_config.stdout_lines }}"
      run_once: true

    - name: Read list of installed Ansible collections
      ansible.builtin.command: ansible-galaxy collection list
      register: collection_list
      changed_when: false
      delegate_to: localhost
      run_once: true

    - name: Display list of installed Ansible collections
      ansible.builtin.debug:
        msg: "{{ collection_list.stdout_lines }}"
      run_once: true

    - name: Read local environment variables
      ansible.builtin.command: env
      register: local_env
      changed_when: false
      delegate_to: localhost
      run_once: true

    - name: Display local environment variables
      ansible.builtin.debug:
        msg: "{{ local_env.stdout_lines }}"
      run_once: true

    - name: Clear facts
      ansible.builtin.meta: clear_facts

    - name: Display connection parameters
      vars:
        conn_port: "{{ 'ansible_' + ansible_connection + '_port' }}"
        remo_port: "{{ lookup('vars', conn_port, default='')
                       | default(ansible_port, true)
                       | default('22', true) }}"
        conn_user: "{{ 'ansible_' + ansible_connection + '_user' }}"
        remo_user: "{{ lookup('vars', conn_user, default='')
                       | default(ansible_user, true)
                       | default(lookup('env', 'USER'), true) }}"
      ansible.builtin.debug:
        msg: "Attempting to connect as {{ remo_user }} to {{ inventory_hostname }}:{{ remo_port }}"

    - name: Gather POSIX facts
      #become: true
      ansible.builtin.setup:
      ignore_errors: true
      ignore_unreachable: true

    - name: Gather Windows facts
      #become: true
      vars:
        ansible_shell_type: powershell
      ansible.builtin.setup:
      ignore_errors: true
      ignore_unreachable: true
      when: ansible_facts | length == 0

    - name: Display facts
      ansible.builtin.debug:
        var: ansible_facts
