---
- name: Debug playbook example
  hosts: all
  become: false
  gather_facts: true
  tasks:
    - name: Display Ansible configuration basics
      ansible.builtin.debug:
        msg: |
          ansible_version: {{ ansible_version }}
          ansible_config_file: {{ ansible_config_file }}
          ansible_inventory_sources: {{ ansible_inventory_sources }}
          ansible_play_hosts_all: {{ ansible_play_hosts_all }}
          ansible_play_batch: {{ ansible_play_batch }}
      run_once: true

    - name: Display Ansible host groups
      ansible.builtin.debug:
        var: groups
      run_once: true

    - name: Display facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Display variable names
      ansible.builtin.debug:
        msg: "{{ lookup('varnames', '.+', wantlist=true)
                 | reject('in', ['ansible_facts', 'hostvars', 'play_hosts', 'vars'])
                 | sort }}"

    - name: Set variable names to display
      ansible.builtin.set_fact:
        var_names: "{{ lookup('varnames', '.+', wantlist=true)
                       | reject('in', ['ansible_facts', 'hostvars', 'play_hosts', 'vars'])
                       | sort }}"

    - name: Display variables
      vars:
        var_values: |
          {% for key in var_names %}
          {{ key }}: {{ lookup('vars', key) }}
          {% endfor %}
      ansible.builtin.debug:
        msg: "{{ var_values | from_yaml }}"

    - name: Display environment variables
      ansible.builtin.debug:
        msg: |
          MY_VAR1: {{ lookup('ansible.builtin.env', 'MY_VAR1') | default('unset') }}
          MY_VAR2: {{ lookup('ansible.builtin.env', 'MY_VAR2') | default('unset') }}
          MY_VAR3: {{ MY_VAR3 | default('unset') }}
          MY_VAR4: {{ MY_VAR4 | default('unset') }}

    - name: Read list of installed Ansible collections
      ansible.builtin.command: ansible-galaxy collection list
      register: collection_list
      changed_when: false
      delegate_to: localhost
      run_once: true

    - name: Display list of installed Ansible collections
      ansible.builtin.debug:
        var: collection_list.stdout
      delegate_to: localhost
      run_once: true
