#!/usr/bin/env python3

import os
import sys
import shlex
import subprocess

filelist = set()
for path in (sys.argv[1:] or [os.path.curdir]):
    if os.path.isfile(path) or os.path.islink(path):
        filelist.add(os.path.relpath(path))
    elif os.path.isdir(path):
        for root, subdirs, files in os.walk(path):
            if '.git' in subdirs:
                subdirs.remove('.git')
            for file in files:
                filelist.add(os.path.relpath(os.path.join(root, file)))

gitdif = subprocess.Popen(shlex.split('git diff --name-status'),
                          stdout=subprocess.PIPE)
changed = []
for line in gitdif.stdout:
    if line.decode('UTF-8').startswith('M'):
        changed.append(line.decode('UTF-8').split()[1])
gitdif.wait()

gitobj = subprocess.Popen(shlex.split('git log --no-merges --raw --pretty=%at'),
                          stdout=subprocess.PIPE)
mtime = 0
for line in gitobj.stdout:
    line = line.decode('UTF-8')
    line = line.strip()
    if not line:
        continue

    if line.startswith(':'):
        file = line.split('\t')[-1]
        if file in filelist:
            filelist.remove(file)
            if file not in changed:
                try:
                    os.utime(file, (mtime, mtime))
                except Exception:
                    pass
    else:
        mtime = int(line)

    if not filelist:
        break
gitobj.terminate()
gitobj.wait()

for root, dirs, files in os.walk(os.path.curdir, topdown=False):
    if '.git' in root.split(os.sep):
        continue

    paths = [os.path.join(root, x) for x in dirs + files if x != '.git']

    try:
        latest_mtime = max(
            (os.path.getmtime(p) for p in paths if os.path.exists(p)),
            default=None
        )
        if latest_mtime is not None:
            os.utime(root, (latest_mtime, latest_mtime))

    except Exception:
        pass
