#!/bin/sh

# https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#node-requirement-summary
# https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix

# Config
ANSIBLE_FLAVOR=ansible-core
BASE_DIR=$HOME/ansible
PYTHON_BIN=python3.11
VERSIONS="2.16 2.18 2.19"
PRE_RELEASES=no

# Main
mkdir -p $BASE_DIR || exit 2
cd $BASE_DIR || exit 3
for ver in $VERSIONS; do
  inst_dir=ansible-$ver
  flavor=$ANSIBLE_FLAVOR
  py_bin=$PYTHON_BIN

  ver_limit="==$ver.*"

  if ! command -v $py_bin > /dev/null 2>&1 ; then
    echo "Python executable $py_bin not found!" 1>&2
    exit 1
  fi

  if [ "$PRE_RELEASES" = "yes" ]; then
    pre_option="--pre"
  fi

  echo Setting up $py_bin venv for $flavor-$ver...
  if [ ! -d $inst_dir ]; then
    mkdir -p $inst_dir || exit 4
    $py_bin -m venv $inst_dir || exit 5
  fi
  . $BASE_DIR/$inst_dir/bin/activate
  $py_bin -m pip install --upgrade pip wheel
  $py_bin -m pip install --upgrade $pre_option $flavor$ver_limit
  $py_bin -m pip install --upgrade ansible-dev-environment ansible-lint passlib
  $py_bin -m pip install --upgrade pypsrp pywinrm requests-credssp requests-ntlm
  rpm -q gcc krb5-devel ${py_bin}-devel > /dev/null 2>&1 &&
    $py_bin -m pip install --upgrade pykerberos
  deactivate
done
