#!/bin/sh

# https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#node-requirement-summary
# https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix

# Config
ANSIBLE_FLAVOR=ansible-core
BASE_DIR=$HOME/ansible
PYTHON_BIN=python3.9
VERSIONS="2.9 2.13 2.15"

# Main
mkdir -p $BASE_DIR || exit 2
cd $BASE_DIR || exit 3
for ver in $VERSIONS; do
  ansible_dir=ansible-$ver
  flavor=$ANSIBLE_FLAVOR
  full_ver=$(expr $(echo $ver | cut -d. -f2) - 7)
  full_ver_limit=$(expr $(echo $full_ver) + 1)

  if [ "$ver" = "2.9" ]; then
    flavor=ansible
    full_ver_limit="2.10"
    #PYTHON_BIN=python3.8
  else
    want_lint="ansible-lint"
  fi

  if [ "$flavor" = "ansible-core" ]; then
    ver_limit="==$ver.*"
  else
    ver_limit="<$full_ver_limit"
  fi

  if ! command -v $PYTHON_BIN > /dev/null 2>&1 ; then
    echo "Python executable $PYTHON_BIN not found!" 1>&2
    exit 1
  fi

  echo Setting up venv for $flavor-$ver...
  if [ ! -d $ansible_dir ]; then
    mkdir -p $ansible_dir || exit 4
    $PYTHON_BIN -m venv $ansible_dir || exit 5
  fi
  . $BASE_DIR/$ansible_dir/bin/activate
  $PYTHON_BIN -m pip install --upgrade pip wheel
  $PYTHON_BIN -m pip install --upgrade $flavor$ver_limit $want_lint passlib
done
