#!/bin/sh

# https://docs.ansible.com/ansible/latest/collections_guide/collections_installing.html#installing-collections-with-signature-verification
# https://docs.ansible.com/ansible/latest/collections_guide/collections_verifying.html#verifying-signed-collections
# https://console.redhat.com/ansible/automation-hub/token
# https://access.redhat.com/security/team/key

# Config
BASE_PATH=$HOME/.ansible
export GNUPGHOME=$BASE_PATH/gnupg

# Setup Ansible GPG keyring with Red Hat public collections key
curl -sLO https://access.redhat.com/security/data/8a828aad.txt
mkdir -m 0700 -p $GNUPGHOME
# NB. It's safe to ignore the "invalid armor header" warning
gpg --import ./8a828aad.txt 2>&1 | grep -v "invalid armor header"
rm -rf $GNUPGHOME/private-keys-v1.d $GNUPGHOME/pubring.kbx~
rm -f ./8a828aad.txt

echo
echo "Now set 'gpg_keyring = $GNUPGHOME/pubring.kbx' in the [galaxy] section of ansible.cfg."
echo "Optionally, export GNUPGHOME=$BASE_PATH/gnupg before running ansible-galaxy collection,"
echo "this would ensure that ~/.gnupg will not be used in any way with ansible-galaxy."
