#!/bin/sh

if [ "$1" = "" ]; then
  echo "Usage: $(basename $0) <host_fqdn>" 1>&2
  exit 1
fi

HOST=$(echo "$1" | cut -d'.' -f1)
FQDN="$1"

cat << EOF > cert.cfg
expiration_days = 3650
cn = $FQDN
dns_name = $HOST
dns_name = $FQDN
tls_www_server
signing_key
encryption_key
EOF

certtool --generate-privkey --template cert.cfg --outfile $FQDN-key.pem

certtool --generate-certificate --template cert.cfg \
  --load-ca-certificate signing-cert.pem --load-ca-privkey signing-key.pem \
  --load-privkey $FQDN-key.pem --outfile $FQDN-cert.pem

certtool --verify --verify-profile high \
  --load-ca-certificate signing-cert.pem --infile $FQDN-cert.pem

rm -f cert.cfg
